const OUTPUT_FOLDER_ID = LandGasterId.DCA_OUTPUT_FOLDER_ID();
const TEMPLATE_FILE_ID = LandGasterId.DCA_TEMPLATE_FILE_ID();
const OUTPUT_FOLDER_ID_BY_DUPLICATION = LandGasterId.DCA_OUTPUT_FOLDER_ID_BY_DUPLICATION();

const LOG_GETTING_SHEET_URL = LandGasterId.GC_LOG_GETTING_SHEET_URL();
